# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hui's Blog
subtitle: I'm not a Cobain, So try harder.
description: 好记性不如烂笔头。
#author: 刘庆辉
author: 撸码
language: zh-Hans
timezone:



#文章目录
toc:
  enable: true
  maxDepth: 3 //表示目录深度为3，即最多生成三级目录
  slugify: false
  number: false


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://52lu.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
#theme: landscape
#theme: next
theme: 3-hexo

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
#  repo: https://github.com/52lu/52lu.github.io.git
  repo: https://github.com/52lu/52lu.github.io..git
  barnch: hexo

#search
search:
  path: search.xml
  field: post
  format: html
  limit: 100

# 网易云音乐
wangyiCloudMusic:
  enable: true
#  成都
#  url: //music.163.com/outchain/player?type=2&id=436514312&auto=1&height=66
  url: //music.163.com/outchain/player?type=2&id=449578837&auto=1&height=66
